### Task Description
-   The objective of this notebook is to help you build a strong foundation in using NumPy, a powerful library in Python for numerical and matrix operations. This notebook is divided into four tasks:

#### Task 1: Basic Array Operations
-   Learn the basics of creating and manipulating 1D and 2D arrays, including reshaping, slicing, and performing basic statistical operations.

#### Task 2: Element-wise Operations and Array Manipulations
-  Practice element-wise operations like addition, subtraction, multiplication, and division on matrices. Additionally, explore matrix manipulation techniques like transposing and finding the dot product.

#### Task 3: Filtering and Boolean Indexing
-   Understand how to use Boolean indexing to filter out data and modify elements in an array based on certain conditions.

#### Task 4: Linear Algebra Operations
-   Explore NumPy’s capabilities in linear algebra by computing determinants, inverses, eigenvalues, and eigenvectors of a matrix.



In [1]:
# Import necessary libraries
import numpy as np

### Task 1: Basics of NumPy Arrays and Simple Operations
-   Objective: Learn the basics of NumPy arrays and simple operations.

-   Step 1: Create a 1D NumPy array with numbers from 1 to 20

In [2]:
array_1d = np.arange(1, 21)
print("1D Array:", array_1d)


1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


-   Step 2: Create a 2D array of shape (3, 5) with random integers between 10 and 50

In [3]:
array_2d = np.random.randint(10, 50, size=(3, 5))
print("2D Array:\n", array_2d)


2D Array:
 [[41 48 11 42 22]
 [21 23 32 49 13]
 [27 43 37 24 49]]


-   Step 3: Extract the first and third rows of the 2D array

In [4]:
first_third_rows = array_2d[[0, 2], :]
print("First and Third Rows:\n", first_third_rows)


First and Third Rows:
 [[41 48 11 42 22]
 [27 43 37 24 49]]


-    Step 4: Calculate the sum, mean, minimum, and maximum of the entire 2D array

In [5]:
array_sum = np.sum(array_2d)
array_mean = np.mean(array_2d)
array_min = np.min(array_2d)
array_max = np.max(array_2d)
print(f"Sum: {array_sum}, Mean: {array_mean}, Min: {array_min}, Max: {array_max}")


Sum: 482, Mean: 32.13333333333333, Min: 11, Max: 49


-   Step 5: Reshape the 1D array into a 4x5 matrix

In [6]:
reshaped_array = array_1d.reshape(4, 5)
print("Reshaped 4x5 Matrix:\n", reshaped_array)


Reshaped 4x5 Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


### Task 2: Element-wise Operations and Array Manipulations
-   Objective: Practice element-wise operations and array manipulations.

-   Step 1: Create two random 3x3 matrices

In [7]:
matrix_a = np.random.rand(3, 3)
matrix_b = np.random.rand(3, 3)
print("Matrix A:\n", matrix_a)
print("Matrix B:\n", matrix_b)


Matrix A:
 [[0.35566091 0.02733861 0.03929855]
 [0.8888192  0.58665037 0.5569696 ]
 [0.32713518 0.71594588 0.77518281]]
Matrix B:
 [[0.32935471 0.04662031 0.74803333]
 [0.60361392 0.2673274  0.01977813]
 [0.46869094 0.24989115 0.5082403 ]]


-   Step 2: Perform element-wise operations on these matrices
(a) Addition

In [8]:
addition = matrix_a + matrix_b
print("Addition:\n", addition)


Addition:
 [[0.68501562 0.07395892 0.78733188]
 [1.49243313 0.85397778 0.57674773]
 [0.79582612 0.96583704 1.28342311]]


-   (b) Subtraction

In [9]:
subtraction = matrix_a - matrix_b
print("Subtraction:\n", subtraction)


Subtraction:
 [[ 0.02630621 -0.0192817  -0.70873479]
 [ 0.28520528  0.31932297  0.53719147]
 [-0.14155576  0.46605473  0.26694251]]
