## Lab 08 Chi square Teasting


#### Example 01:


In [1]:
import numpy as np
from scipy.stats import chi2

In [2]:
#observed frequency 
observed = np.array([50,30,30,10])
expected = np.array([30,30,30,30])
chi2_stat = 0
df = len(observed) - 1
aplha = 0.05
for x in range(len(observed)):
    a = observed[x] - expected[x]
    a = a*a
    a = a/expected[x]
    chi2_stat += a

chi2_critical = chi2.ppf(1-aplha,df)

print(f"the chi sqr statistic is {chi2_stat}\nand the critcial value is {chi2_critical}")

if chi2_critical > abs(chi2_stat):
    print("Not reject Null Hypothisis")
else:
    print("Reject Null Hypothesis")


the chi sqr statistic is 26.666666666666668
and the critcial value is 7.814727903251179
Reject Null Hypothesis


### Example 2

In [3]:
#observed frequency 
observed = np.array([[10,50,35],[15,60,40]])
rows, columns = observed.shape

row_totals = np.sum(observed, axis=1)
column_totals = np.sum(observed, axis=0)
total = np.sum(row_totals)

product_matrix = np.outer(row_totals, column_totals)
expected = product_matrix / total
df = (rows - 1)*(columns - 1)

print(f"Observed = {observed}\n\nExpected = {expected}\n\nDegree of Freedom = {df}\n")

chi_score = np.sum((observed - expected)**2 / expected)
chi_critical = chi2.ppf(1 - aplha, df)

print(f"Chi2 Score = {chi_score}\nChi2_critical = {chi_critical}\n\n")
if chi_critical > abs(chi_score):
    print("do Not reject Null Hypothisis")
else:
    print("Reject Null Hypothesis")


Observed = [[10 50 35]
 [15 60 40]]

Expected = [[11.30952381 49.76190476 33.92857143]
 [13.69047619 60.23809524 41.07142857]]

Degree of Freedom = 2

Chi2 Score = 0.3407530684418557
Chi2_critical = 5.991464547107979


do Not reject Null Hypothisis


### Example 3
Chi-Square test for independence- An Example

In [4]:
observed = np.array([[12, 108],[24, 156]])
rows, columns = observed.shape

row_totals = np.sum(observed, axis=1)
column_totals = np.sum(observed, axis=0)
total = np.sum(row_totals)

product_matrix = np.outer(row_totals, column_totals)

expected = product_matrix / total
df = (rows - 1)*(columns - 1)

print(f"Observed = {observed}\n\nExpected = {expected}\n\nDegree of Freedom = {df}\n")

chi_score = np.sum((observed - expected)**2 / expected)
chi_critical = chi2.ppf(1 - aplha, df)

print(f"Chi2 Score = {chi_score}\nChi2_critical = {chi_critical}\n\n")
if chi_critical > abs(chi_score):
    print("do Not reject Null Hypothisis")
else:
    print("Reject Null Hypothesis")

Observed = [[ 12 108]
 [ 24 156]]

Expected = [[ 14.4 105.6]
 [ 21.6 158.4]]

Degree of Freedom = 1

Chi2 Score = 0.7575757575757577
Chi2_critical = 3.841458820694124


do Not reject Null Hypothisis


### Example 04
The meal plan selected by 200 students

In [5]:
observed = np.array([[24, 32, 14], [22, 26, 12], [10, 14, 6], [14, 16, 10]])
rows, columns = observed.shape

row_totals = np.sum(observed, axis=1)
column_totals = np.sum(observed, axis=0)
total = np.sum(row_totals)

product_matrix = np.outer(row_totals, column_totals)

expected = product_matrix / total
df = (rows - 1)*(columns - 1)

print(f"Observed = {observed}\n\nExpected = {expected}\n\nDegree of Freedom = {df}\n")

chi_score = np.sum((observed - expected)**2 / expected)
chi_critical = chi2.ppf(1 - aplha, df)

print(f"Chi2 Score = {chi_score}\nChi2_critical = {chi_critical}\n\n")
if chi_critical > abs(chi_score):
    print("do Not reject Null Hypothisis")
else:
    print("Reject Null Hypothesis")

Observed = [[24 32 14]
 [22 26 12]
 [10 14  6]
 [14 16 10]]

Expected = [[24.5 30.8 14.7]
 [21.  26.4 12.6]
 [10.5 13.2  6.3]
 [14.  17.6  8.4]]

Degree of Freedom = 6

Chi2 Score = 0.7093382807668522
Chi2_critical = 12.591587243743977


do Not reject Null Hypothisis


### Example 05
Award Preference & SAT

In [6]:
observed = np.array([[21, 68, 116],[10, 79, 61]])
rows, columns = observed.shape

row_totals = np.sum(observed, axis=1)
column_totals = np.sum(observed, axis=0)
total = np.sum(row_totals)

product_matrix = np.outer(row_totals, column_totals)
expected = product_matrix / total
df = (rows - 1)*(columns - 1)

print(f"Observed = {observed}\n\nExpected = {expected}\n\nDegree of Freedom = {df}\n")
chi_score = np.sum((observed - expected)**2 / expected)
chi_critical = chi2.ppf(1 - aplha, df)

print(f"Chi2 Score = {chi_score}\nChi2_critical = {chi_critical}\n\n")
if chi_critical > abs(chi_score):
    print("do Not reject Null Hypothisis")
else:
    print("Reject Null Hypothesis")

Observed = [[ 21  68 116]
 [ 10  79  61]]

Expected = [[ 17.90140845  84.88732394 102.21126761]
 [ 13.09859155  62.11267606  74.78873239]]

Degree of Freedom = 2

Chi2 Score = 13.622609647147335
Chi2_critical = 5.991464547107979


Reject Null Hypothesis


### Example 06
- Is there a preference for ice cream flavors among different age groups?

In [7]:
observed = np.array([[35, 25, 15],[20, 30, 20], [25, 20, 25]])
rows, columns = observed.shape

row_totals = np.sum(observed, axis=1)
column_totals = np.sum(observed, axis=0)
total = np.sum(row_totals)

product_matrix = np.outer(row_totals, column_totals)
expected = product_matrix / total
df = (rows - 1)*(columns - 1)

print(f"Observed = {observed}\n\nExpected = {expected}\n\nDegree of Freedom = {df}\n")
chi_score = np.sum((observed - expected)**2 / expected)
chi_critical = chi2.ppf(1 - aplha, df)

print(f"Chi2 Score = {chi_score}\nChi2_critical = {chi_critical}\n\n")
if chi_critical > abs(chi_score):
    print("do Not reject Null Hypothisis")
else:
    print("Reject Null Hypothesis")

Observed = [[35 25 15]
 [20 30 20]
 [25 20 25]]

Expected = [[27.90697674 26.1627907  20.93023256]
 [26.04651163 24.41860465 19.53488372]
 [26.04651163 24.41860465 19.53488372]]

Degree of Freedom = 4

Chi2 Score = 8.595734126984128
Chi2_critical = 9.487729036781154


do Not reject Null Hypothisis


### Example 07
Are the outcomes of a six-sided die roll equally distributed?

In [8]:
#observed frequency 
observed = np.array([15, 20, 10, 18, 12, 25])
expected = np.array([16.67, 16.67, 16.67, 16.67, 16.67, 16.67])
chi2_stat = 0
df = len(observed) - 1
aplha = 0.05
for x in range(len(observed)):
    a = observed[x] - expected[x]
    a = a*a
    a = a/expected[x]
    chi2_stat += a

chi2_critical = chi2.ppf(1-aplha,df)
print(f"the chi sqr statistic is {chi2_stat}\nand the critcial value is {chi2_critical}")

if chi2_critical > abs(chi2_stat):
    print("Not reject Null Hypothisis")
else:
    print("Reject Null Hypothesis")


the chi sqr statistic is 9.078188362327534
and the critcial value is 11.070497693516351
Not reject Null Hypothisis


### Example 08

Does the choice of transportation (Car, Bike, Walk) vary by region (Urban, 
Suburban, Rural)?

In [9]:
observed = np.array([[40, 30, 20],[50, 20, 10], [30, 10, 60]])
rows, columns = observed.shape

row_totals = np.sum(observed, axis=1)
column_totals = np.sum(observed, axis=0)
total = np.sum(row_totals)

product_matrix = np.outer(row_totals, column_totals)

expected = product_matrix / total
df = (rows - 1)*(columns - 1)

print(f"Observed = {observed}\n\nExpected = {expected}\n\nDegree of Freedom = {df}\n")
chi_score = np.sum((observed - expected)**2 / expected)
chi_critical = chi2.ppf(1 - aplha, df)
print(f"Chi2 Score = {chi_score}\nChi2_critical = {chi_critical}\n\n")
if chi_critical > abs(chi_score):
    print("do Not reject Null Hypothisis")
else:
    print("Reject Null Hypothesis")

Observed = [[40 30 20]
 [50 20 10]
 [30 10 60]]

Expected = [[40.         20.         30.        ]
 [35.55555556 17.77777778 26.66666667]
 [44.44444444 22.22222222 33.33333333]]

Degree of Freedom = 4

Chi2 Score = 57.64583333333333
Chi2_critical = 9.487729036781154


Reject Null Hypothesis


### Example 09
- Are the observed and expected distributions of grades in a class 
significantly different?


In [10]:
#observed frequency 
observed = np.array([15, 30, 40, 10, 5])
expected = np.array([20, 30, 30, 10, 10])
chi2_stat = 0
df = len(observed) - 1
aplha = 0.05
for x in range(len(observed)):
    a = observed[x] - expected[x]
    a = a*a
    a = a/expected[x]
    chi2_stat += a

chi2_critical = chi2.ppf(1-aplha,df)
print(f"the chi sqr statistic is {chi2_stat}\nand the critcial value is {chi2_critical}")

if chi2_critical > abs(chi2_stat):
    print("Not reject Null Hypothisis")
else:
    print("Reject Null Hypothesis")


the chi sqr statistic is 7.083333333333334
and the critcial value is 9.487729036781154
Not reject Null Hypothisis
